name: scanbot-frontend-nextjs
description: Frontend service for Scanbot project built with Next.js
ignoreFiles: .git .next node_modules
modules:
  - name: nextjs
    language: nodejs18.x
    web: nextjs
    description: NodeJS v18.x module using Next.js v13.x
    functions:
      - name: entry
        description: the entry point for the function