name: scanbotlite-frontend
description: Frontend service for Scanbot project built with Next.js
ignoreFiles: .git .next node_modules
modules:
  - name: nextjs
    language: nodejs20.x
    web: next.standalone
    description: NodeJS v18.x module using Next.js v13.x
    config:
      instance: ombMirIBXO
    functions:
      - name: entry
        description: the entry point for the function