name: scanbotlite-backend
description: Backend service for Scanbot project built with Express.js
ignoreFiles: .git node_modules
modules:
- name: container
  language: docker
  description: NodeJS v18.x module using Express web framework v4.x
  ports:
    - alias: "http"
      port: 8000
  functions:
    - name: entry
      description: the entry point for the function
